# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: img2FGC Compilation

on:
  pull_request:
    branches: ['Releases']
  pull_request_review:
    branches: ['Releases']
    types: [ submitted ]


jobs:
  build:
    name: Compile img2FGC
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          architecture: 'x64'
          cache: 'pip'

      - name: Install requirements.txt
        run: pip install -r requirements.txt

      - name: Build img2FGC
        run: nuitka --onefile --standalone --clang --file-version=1.0.0.52 --product-version=1.0.0.52 --warn-unusual-code --show-anti-bloat-changes --assume-yes-for-downloads --warn-implicit-exceptions --include-package=img2FGC --output-dir=dist --product-name="Image To FGC" --file-description="Image To FGC" --windows-icon-from-ico=img2FGC/icon.ico --enable-plugin=pylint-warnings .\img2FGC

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Python Build
          path: dist/*.exe
