# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: img2FGC Compilation

on:
  pull_request:
    branches: ['Releases']
  pull_request_review:
    branches: ['Releases']
    types: [ submitted ]


jobs:
  build:
    name: Compile img2FGC
    runs-on: windows-latest

    steps:
      - name: Check-out repository
        uses: actions/checkout@v4
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12.7'
          architecture: 'x64'
          cache: 'pip'

      - name: Install requirements.txt
        run: |
          pip install -r requirements.txt
          cd src

      - name: Build executables or extension modules from Python projects
        uses: Nuitka/Nuitka-Action@v1.1
        with:
          nuitka-version: main
          script-name: img2FGC
          onefile: true
          standalone: true
          clang: true
          warn-unusual-code: true
          show-anti-bloat-changes: true
          assume-yes-for-downloads: true
          warn-implicit-exceptions: true
          enable-plugin: pylint-warnings
          include-package: img2FGC
          output-dir: dist
          product-name: Image To FGC
          file-description: Image To FGC
          file-version: 1.0.0.52
          product-version: 1.0.0.52
          windows-icon-from-ico: img2FGC/icon.png
      # - run: wheel unpack wheels/JPB*.whl # 7z a -mx1 -ms64m -sfx test.7z .\*

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ runner.os }} Python Build
          path: dist/*.exe

      - if: github.event.review.state == 'approved'
        name: Upload files to a GitHub release
        uses: svenstaro/upload-release-action@2.9.0
        with:
          file: dist/*.exe